name: GitHub Hosted Test
on: workflow_dispatch
jobs:
  test:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Style checks
      run: |
        sudo chmod 755 ghaction_script.sh
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        ./ghaction_script.sh
         
