name: Self-hosted test
on: workflow_dispatch
jobs:
  test:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Test script
    - name: Test script
      timeout-minutes: 1
      shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
      run: |
        sudo chmod 755 ghaction_script.sh
        ./ghaction_script.sh
         
