name: CI
on:
  push:
    branches:
      - main
jobs:
  test:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Style checks
      run: |
        sudo chmod 755 ghaction_script.sh
        ./ghaction_script.sh
         
